### ISSUE TITLE
About wechat emotion export

### ISSUE THREAD

**Issue by wangzhx123** [cxun/WeChatHistory#2]
I've read your blog post (http://www.cnblogs.com/cxun/p/4338643.html) introducing this  WeChat message export software. It's really helpful and useful as is your article. I have some issues concerning the emotion display.

Quote from your article, you said that ——"除了这两种表情以外，微信用户还经常看到许多非官方表情，如果想在这软件里显示的话，需要进行额外的数据导出工作，也不复杂：照样使用 iTools 打开微信App的这个目录：/Library/WechatPrivate/emoticon1，将此文件夹复制到本软件的安装目录，覆盖原有的 emoticon1 文件夹即可。"

However, I cannot find such directory on my iPhone device via iTools. And I have also searched the WeChat app folder, still couldn't find any clues about where WeChat app store the emotion images. Hope you can give some help. 

Thank you very much.

**Comment by wangzhx123** [comment]
Sorry, I have found it.
Thank you!

**Comment by cxun** [comment]
Okay, anytime~
