### ISSUE TITLE
System.OverflowException: 值对于 Int16 太大或太小

### ISSUE THREAD

**Issue by deng00** [cxun/WeChatHistory#3]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

*************\* 异常文本 **************
System.OverflowException: 值对于 Int16 太大或太小。
   在 System.Convert.ToInt16(Int32 value)
   在 System.Data.SQLite.SQLiteDataReader.GetInt16(Int32 i)
   在 WechatHistory.MainForm.MainForm_Load(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.ContainerControl.WndProc(Message& m)
   在 System.Windows.Forms.Form.WmShowWindow(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by cxun** [comment]
你好，此BUG已在1.0.1.4版本中修复，谢谢。

**Comment by cxun** [comment]
![fix_bug](https://cloud.githubusercontent.com/assets/5934861/10361663/23c3fb46-6ddc-11e5-99ed-74a11d410656.png)

**Comment by deng00** [comment]
建议更新下博客里的下载链接吧，我之前是从博客下载的旧版本，没注意新版已经修复了。
http://www.cnblogs.com/cxun/p/4338643.html

**Comment by cxun** [comment]
谢谢提醒，已更新博文。
