### ISSUE TITLE
请问能否支持查看已删除的对话消息？

### ISSUE THREAD

**Issue by babesun** [cxun/WeChatHistory#4]
网上已经有类似的软件在卖，但是来路不明不敢用，比如楼月、Fenlog，而且楼主的软件做得更直观、更人性化，支持你！

**Comment by cxun** [comment]
@Babesun 你好，目前不支持查看已删除的聊天记录，因为删除操作对应的数据库操作就是删除某个Table，而本软件就是将现有的数据库呈现出来。不过听说删除操作只是将表名删除而已，被删除的表数据还存在于数据库文件中，如果数据没被覆盖，理论上是可以恢复这些数据的。但这也只是我看过的资料中得到的结论，目前本软件没有这个功能。谢谢你的支持！
